name: Build OpenSSL for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Optional: override these if needed
      ANDROID_NDK_VERSION: 26.0.10792818

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl tar llvm make

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}

      - name: Show NDK location
        run: |
          echo "NDK location: $ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}"
          ls $ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}

      - name: Build OpenSSL for all Android ABIs
        env:
          NDK_ROOT_PREFIX: ${{ env.ANDROID_HOME }}/ndk
        run: |
          chmod +x ./build-openssl.sh
          ./build-openssl.sh

      - name: Collect .so files for upload
        run: |
          mkdir -p artifacts
          find build -name "*.so" -exec cp --parents {} artifacts/ \;

      - name: Upload OpenSSL .so artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-openssl-libs
          path: artifacts/
