name: Build OpenSSL for Android

on:
  workflow_dispatch:

jobs:
  build-openssl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential python3 llvm

      - name: Make build script executable
        run: chmod +x build_ssl.sh

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          packages: ndk;26.0.10792818

      - name: Show available NDKs
        run: ls $ANDROID_HOME/ndk

      - name: Build all OpenSSL ABIs
        env:
          OUTPUT_ROOT: ${{ github.workspace }}/output
          BUILD_DIR: ${{ github.workspace }}/build
          NDK_ROOT_PREFIX: $ANDROID_HOME/ndk
        run: |
          ./build_ssl.sh

      - name: List build output
        run: ls -lR output

      - name: Upload OpenSSL Android outputs
        uses: actions/upload-artifact@v4
        with:
          name: openssl-android
          path: output/
